# the package build type(SHARED/STATIC/EXE/WIN32EXE/FRAMEWORK/BINARY/MACOSX_BUNDLE)
if(IOS_PLATFORM)
    set(LEMON_PACKAGE_TYPE STATIC)
else()
    set(LEMON_PACKAGE_TYPE SHARED)
endif()

set(LEMON_PACKAGE_VERSION "1.0.*")

set(LEMON_PACKAGE_EXE_NAME lnode)


if(ANDROID)
    set(LEMON_PACKAGE_LINK_LIBRARIES log m)
endif()
