# the package build type(SHARED/STATIC/EXE/WIN32EXE/FRAMEWORK/BINARY)
set(LEMON_PACKAGE_TYPE SHARED)

set(LEMON_PACKAGE_VERSION "1.0.*")

set(LEMON_PACKAGE_EXE_NAME lemoon) 

set(LEMON_PACKAGE_LINK_LIBRARIES lua lemoonxx)


