# the package build type(SHARED/STATIC/EXE/WIN32EXE/FRAMEWORK/BINARY)
set(LEMON_PACKAGE_TYPE SHARED)

set(LEMON_PACKAGE_VERSION "1.0.*")

if(NOT WIN32)
	set(LEMON_PACKAGE_LINK_LIBRARIES dl)
endif()


